---

- hosts: all
  become: true
  tasks:

  - name: Basic Linux tools set up (Debain, Ubuntu)
    tags: debian,ubuntu,basic,tools
    apt:
      name:
        - tmux
        - python3
        - htop
        - git
        - vim-nox
        - python3-pip
      state: latest
      update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

